export enum DigimonStatusType {
    Strength = "Strength",
    Defense = "Defense",
    Spirit = "Spirit",
    Wisdom = "Wisdom",
    Speed = "Speed",
    Charisma = "Charisma",
    Fire = "Fire",
    Water = "Water",
    Ice = "Ice",
    Wind = "Wind",
    Thunder = "Thunder",
    Machine = "Machine",
    Dark = "Dark",
}
