export { AuctionRepository } from "./auction.repository";
export { EquipmentRepository } from './equipment.repository';
export { DigimonRepository } from "./digimon.repository";
export { DigievolutionRepository } from "./digievolution.repository";
export { QuestRepository as JournalRepository } from "./quest.repository";
export { LocationRepository } from "./location.repository";
export { DockRepository } from "./dock.repository";
export { SeabedDirectionsRepository as SeabedDirectionRepository } from "./seabed-direction.repository";
export { SeabedRoutesRepository } from "./seabed-routes.repository";
export { DesertAreasRepository } from "./desert-areas.repository";
export { DesertAreasMapRepository } from "./desert-areas-map.repository";
