export enum Constants {
    strength = "strength",
    defense = "defense",
    spirit = "spirit",
    wisdom = "wisdom",
    speed = "speed",
    charisma = "charisma",
    fire = "fire",
    water = "water",
    ice = "ice",
    wind = "wind",
    thunder = "thunder",
    machine = "machine",
    dark = "dark",
    poison = "poison",
    paralyze = "paralyze",
    confuse = "confuse",
    sleep = "sleep",
    ko = "ko",
    drain = "drain",
    steal = "steal",
    escape = "escape",
    physical = "physical",
    magical = "magical",
    heal = "heal",
    support = "support",
}
