import type { EnemyDropRaw } from "../enemy/enemy-drop.raw";

export interface NpcPartyDigimonRaw {
  name: string;
  level: number;
  hp: number;
  species: string;
  rate: number;
  strength: number;
  defense: number;
  spirit: number;
  wisdom: number;
  speed: number;
  fire: number;
  water: number;
  ice: number;
  wind: number;
  thunder: number;
  machine: number;
  dark: number;
  canPoison: boolean;
  poison: number;
  canParalyze: boolean;
  paralyze: number;
  canConfuse: boolean;
  confuse: number;
  canSleep: boolean;
  sleep: number;
  canKO: boolean;
  ko: number;
  canDrain: boolean;
  canSteal: boolean;
  strDown: string;
  defDown: string;
  spdDown: string;
  canEscape: boolean;
  drops?: EnemyDropRaw[];
  regularAttackId: string | null;
  techniqueId: string | null;
  memoryId: number;
}
